# This file only handles theming of fcitx5.
{ config, lib, pkgs, ... }:

lib.mkIf config.home.roles.desktop.enable {
  xdg.dataFile."fcitx5/themes/nix-theme/theme.conf".source = let c = config.theme.colors; in (pkgs.formats.ini { }).generate "what" {
    "Metadata" = {
      Name = "nix-theme";
      Author = "CartConnoisseur";
      Description = "Theme generated by nixos";
      Version = 1;
    };

    "InputPanel" = {
      NormalColor = "#${c.fg}";
      HighlightColor = "#${c.fg}";
      HighlightBackgroundColor = "#00000000";
      HighlightCandidateColor = "#${c.bg}";

      FullWidthHighlight = true;
      PageButtonAlignment = "Last Candidate";
    };

    "InputPanel/Background" = {
      Color = "#${c.bg}";
      BorderColor = "#${c.fg1}";
      BorderWidth = 2;
    };

    # "InputPanel/Background/Margin" = {
    #   Left = 10;
    #   Right = 10;
    #   Top = 10;
    #   Bottom = 10;
    # };

    "InputPanel/Highlight" = {
      Color = "#${c.fg}";
      BorderWidth = 0;
    };

    "InputPanel/Highlight/Margin" = {
      Left = 2;
      Right = 2;
      Top = 2;
      Bottom = 2;
    };

    "InputPanel/ContentMargin" = {
      Left = 2;
      Right = 2;
      Top = 2;
      Bottom = 2;
    };

    "InputPanel/TextMargin" = {
      Left = 5;
      Right = 5;
      Top = 5;
      Bottom = 5;
    };
  };
}
